create table store
(
    id             int generated by default as identity primary key,
    name           varchar(128)                                                                        not null,
    address        varchar(128) check ( address ~ '^\d{5}, [A-Za-z]{2,25}, [A-Za-z0-9,. ''-]{2,50}$' ) not null,
    edrpou         varchar(8) check ( edrpou ~ '^\d{8}$' ) unique                                      not null,
    special_number varchar(9) check ( special_number ~ '^[A-Z]{2}-\d{6}$' ) unique                     not null,
    description    varchar(256)
);

insert into store(name, address, edrpou, special_number, description)
values
-- Novus
('Novus', '01001, Ukraine, Kyiv, vul. Khreshchatyk, 22', '12345678', 'KV-000001', 'Novus main branch'),
('Novus', '02002, Ukraine, Kyiv, vul. Drahomanova, 10', '23456789', 'KV-000002', 'Novus branch 2'),
('Novus', '03003, Ukraine, Kyiv, vul. Shuliavska, 15', '34567890', 'KV-000003', 'Novus branch 3'),

-- Ashan
('Ashan', '04004, Ukraine, Kyiv, vul. Povitroflotskyi ave., 16', '45678901', 'KV-000004', 'Ashan main branch'),
('Ashan', '05005, Ukraine, Kyiv, vul. Velyka Vasylkivska, 44', '56789012', 'KV-000005', 'Ashan branch 2'),
('Ashan', '06006, Ukraine, Kyiv, vul. Bazhana ave., 20', '67890123', 'KV-000006', 'Ashan branch 3'),

-- ATB
('ATB', '07007, Ukraine, Kyiv, vul. Zhylianska, 40', '78901234', 'KV-000007', 'ATB main branch'),
('ATB', '08008, Ukraine, Kyiv, vul. Sichovykh Striltsiv, 77', '89012345', 'KV-000008', 'ATB branch 2'),
('ATB', '09009, Ukraine, Kyiv, vul. Lvivska, 55', '90123456', 'KV-000009', 'ATB branch 3'),

-- FORA
('FORA', '10010, Ukraine, Kyiv, vul. Boryspilska, 88', '01234567', 'KV-000010', 'FORA main branch'),
('FORA', '11011, Ukraine, Kyiv, vul. Sadova, 101', '12345670', 'KV-000011', 'FORA branch 2'),
('FORA', '12012, Ukraine, Kyiv, vul. Smilyanska, 14', '23456701', 'KV-000012', 'FORA branch 3'),

-- METRO
('METRO', '13013, Ukraine, Kyiv, vul. Brovarskyi ave., 19', '34567012', 'KV-000013', 'METRO main branch'),
('METRO', '14014, Ukraine, Kyiv, vul. Zabolotnoho, 45', '45670123', 'KV-000014', 'METRO branch 2'),
('METRO', '15015, Ukraine, Kyiv, vul. Vokzalna, 72', '56701234', 'KV-000015', 'METRO branch 3');

select * from store;

create table product
(
    id          int generated by default as identity primary key,
    name        varchar(64)                                                 not null,
    article     varchar(9) check ( article ~ '^\d{4}-\d{4}') unique         not null,
    price       numeric(8, 2) check ( price > 0 and price < 100000 )        not null,
    quantity    numeric(7, 2) check ( quantity >= 0 and quantity <= 10000 ) not null,
    description varchar(256),
    store_id    int                                                         references store (id) on delete set null
);
